uploads = []
generated = []

[[outputs]]
id = "iHPE1tubD4I92S5VX7UI_"
uri = "file://shadowweave-export.tar.gz"
type = "unspecified"
title = "SHADOWWEAVE — Full Source Export (118 files, 238 KB)"

[[outputs]]
id = "hIvPDpxIKPVnPoYOt6Jxx"
uri = "file://shadowweave-source.txt"
type = "text"
title = "SHADOWWEAVE — All Source Code (106 files, readable .txt)"
