export interface Heroine {
  name: string;
  alias: string;
  power: string;
  icon: string;
  universe: string;
}

export const ALL_HEROINES: Heroine[] = [
  // ── Marvel ────────────────────────────────────────────────────
  { universe: "Marvel", name: "Black Widow",      alias: "Natasha Romanoff",         power: "Master spy & martial artist",                        icon: "🕸" },
  { universe: "Marvel", name: "Captain Marvel",   alias: "Carol Danvers",            power: "Cosmic energy & flight",                             icon: "⭐" },
  { universe: "Marvel", name: "Storm",            alias: "Ororo Munroe",             power: "Weather manipulation",                               icon: "⚡" },
  { universe: "Marvel", name: "Jean Grey",        alias: "Phoenix",                  power: "Omega-level telepathy & telekinesis",                 icon: "🔥" },
  { universe: "Marvel", name: "Scarlet Witch",    alias: "Wanda Maximoff",           power: "Reality warping chaos magic",                        icon: "🌀" },
  { universe: "Marvel", name: "She-Hulk",         alias: "Jennifer Walters",         power: "Superhuman strength & durability",                   icon: "💚" },
  { universe: "Marvel", name: "Spider-Woman",     alias: "Jessica Drew",             power: "Venom blasts & wall-crawling",                       icon: "🕷" },
  { universe: "Marvel", name: "Rogue",            alias: "Anna Marie",               power: "Power absorption through touch",                     icon: "💜" },
  { universe: "Marvel", name: "Gamora",           alias: "Deadliest Woman",          power: "Peak combat & cybernetic enhancements",              icon: "⚔" },
  { universe: "Marvel", name: "Wasp",             alias: "Janet Van Dyne",           power: "Size manipulation & bio-stings",                     icon: "🐝" },
  { universe: "Marvel", name: "Ms. Marvel",       alias: "Kamala Khan",              power: "Polymorphism & size-shifting",                       icon: "💫" },
  { universe: "Marvel", name: "Invisible Woman",  alias: "Sue Storm",                power: "Invisibility & force fields",                        icon: "🫧" },
  { universe: "Marvel", name: "Psylocke",         alias: "Betsy Braddock",           power: "Psychic blade & telekinesis",                        icon: "🔮" },
  { universe: "Marvel", name: "Emma Frost",       alias: "White Queen",              power: "Telepathy & diamond form",                           icon: "💎" },
  { universe: "Marvel", name: "Ghost-Spider",     alias: "Gwen Stacy",               power: "Spider-powers & web-slinging",                       icon: "🕸" },
  { universe: "Marvel", name: "X-23",             alias: "Laura Kinney",             power: "Bone claws & healing factor",                        icon: "🗡" },
  { universe: "Marvel", name: "Ironheart",        alias: "Riri Williams",            power: "Advanced Iron Man armor",                            icon: "🤖" },
  { universe: "Marvel", name: "America Chavez",   alias: "Miss America",             power: "Star portals & superhuman strength",                 icon: "⭐" },
  { universe: "Marvel", name: "Kate Bishop",      alias: "Hawkeye II",               power: "Master archer & martial artist",                     icon: "🏹" },
  { universe: "Marvel", name: "Valkyrie",         alias: "Brunnhilde",               power: "Asgardian warrior & death-sense",                   icon: "⚔" },
  { universe: "Marvel", name: "Nebula",           alias: "Daughter of Thanos",       power: "Cybernetic body & assassin skills",                  icon: "🌑" },
  { universe: "Marvel", name: "Elektra",          alias: "The Hand's Queen",         power: "Sai mastery & supernatural fighting",                icon: "⚡" },
  { universe: "Marvel", name: "Silk",             alias: "Cindy Moon",               power: "Spider-powers & organic webbing",                    icon: "🕸" },
  { universe: "Marvel", name: "Sif",             alias: "Lady Sif",                  power: "Asgardian warrior goddess",                          icon: "🛡" },
  { universe: "Marvel", name: "Magik",            alias: "Illyana Rasputin",         power: "Soulsword & teleportation discs",                    icon: "✨" },
  { universe: "Marvel", name: "Polaris",          alias: "Lorna Dane",               power: "Magnetic field manipulation",                        icon: "🧲" },
  { universe: "Marvel", name: "Shadowcat",        alias: "Kitty Pryde",              power: "Phasing through solid matter",                       icon: "👻" },
  { universe: "Marvel", name: "Spectrum",         alias: "Monica Rambeau",           power: "Energy form & light manipulation",                   icon: "💡" },
  { universe: "Marvel", name: "Mockingbird",      alias: "Bobbi Morse",              power: "Superhuman agility & battle staves",                 icon: "🥊" },
  { universe: "Marvel", name: "Domino",           alias: "Neena Thurman",            power: "Probability manipulation",                           icon: "🎲" },
  { universe: "Marvel", name: "Firestar",         alias: "Angelica Jones",           power: "Microwave radiation & flight",                       icon: "🔥" },
  { universe: "Marvel", name: "Dazzler",          alias: "Alison Blaire",            power: "Sound-to-light energy conversion",                   icon: "✨" },
  { universe: "Marvel", name: "Black Cat",        alias: "Felicia Hardy",            power: "Bad luck aura & cat-like agility",                   icon: "🐈" },
  { universe: "Marvel", name: "Silver Sable",     alias: "Silver Sablinova",         power: "Elite mercenary & martial artist",                   icon: "💰" },
  { universe: "Marvel", name: "Squirrel Girl",    alias: "Doreen Green",             power: "Unbeatable squirrel-based powers",                   icon: "🐿" },
  { universe: "Marvel", name: "Hellcat",          alias: "Patsy Walker",             power: "Heightened senses & psi-claws",                      icon: "🐱" },
  { universe: "Marvel", name: "Tigra",            alias: "Greer Grant Nelson",       power: "Feline physiology & mystical power",                 icon: "🐯" },
  { universe: "Marvel", name: "Yelena Belova",    alias: "White Widow",              power: "Elite Black Widow agent",                            icon: "⚪" },
  { universe: "Marvel", name: "Mantis",           alias: "Celestial Madonna",        power: "Empathy, precognition & plant control",              icon: "🌿" },
  { universe: "Marvel", name: "Mirage",           alias: "Dani Moonstar",            power: "Psychic illusions & Valkyrie power",                 icon: "🌙" },
  { universe: "Marvel", name: "Jubilee",          alias: "Jubilation Lee",           power: "Plasma fireworks & vampiric power",                  icon: "🎆" },
  { universe: "Marvel", name: "Rachel Grey",      alias: "Marvel Girl",              power: "Omega-level telepath & Hound mark",                  icon: "🦅" },
  { universe: "Marvel", name: "Armor",            alias: "Hisako Ichiki",            power: "Psychic exoskeleton armor",                          icon: "🛡" },
  { universe: "Marvel", name: "Nico Minoru",      alias: "Sister Grimm",             power: "Staff of One sorcery",                               icon: "🔮" },
  { universe: "Marvel", name: "Crystal",          alias: "Crystalia Amaquelin",      power: "Elemental manipulation",                             icon: "🌊" },
  { universe: "Marvel", name: "Medusa",           alias: "Queen of Inhumans",        power: "Prehensile animated hair",                           icon: "👑" },
  { universe: "Marvel", name: "Wolfsbane",        alias: "Rahne Sinclair",           power: "Werewolf transformation",                            icon: "🐺" },
  { universe: "Marvel", name: "Dagger",           alias: "Tandy Bowen",              power: "Light daggers & dreamscaping",                       icon: "🗡" },
  { universe: "Marvel", name: "Spider-Girl",      alias: "Anya Corazon",             power: "Spider-powers & exo-skeleton",                       icon: "🕷" },
  { universe: "Marvel", name: "Phyla-Vell",       alias: "Martyr / Quasar",          power: "Quantum bands & cosmic power",                       icon: "💫" },
  // ── DC ───────────────────────────────────────────────────────
  { universe: "DC", name: "Wonder Woman",     alias: "Diana Prince",                 power: "Amazon warrior & divine power",                      icon: "⚡" },
  { universe: "DC", name: "Supergirl",        alias: "Kara Zor-El",                  power: "Kryptonian powers & solar energy",                   icon: "☀" },
  { universe: "DC", name: "Batgirl / Oracle", alias: "Barbara Gordon",               power: "Genius intellect & fighting mastery",                 icon: "🦇" },
  { universe: "DC", name: "Batwoman",         alias: "Kate Kane",                    power: "Military training & detective skill",                 icon: "🦇" },
  { universe: "DC", name: "Black Canary",     alias: "Dinah Lance",                  power: "Canary Cry & martial artist",                        icon: "🎵" },
  { universe: "DC", name: "Starfire",         alias: "Koriand'r",                    power: "Ultraviolet starbolts & flight",                     icon: "🌟" },
  { universe: "DC", name: "Raven",            alias: "Rachel Roth",                  power: "Dark sorcery & soul-self",                           icon: "🌑" },
  { universe: "DC", name: "Hawkgirl",         alias: "Shayera Hol",                  power: "Nth metal mace & flight",                            icon: "🦅" },
  { universe: "DC", name: "Power Girl",       alias: "Karen Starr",                  power: "Kryptonian strength & durability",                   icon: "💪" },
  { universe: "DC", name: "Zatanna",          alias: "Zatanna Zatara",               power: "Reality-altering backwards spells",                  icon: "🎩" },
  { universe: "DC", name: "Huntress",         alias: "Helena Bertinelli",            power: "Master archer & crime fighter",                      icon: "🏹" },
  { universe: "DC", name: "Catwoman",         alias: "Selina Kyle",                  power: "Cat-like agility & whip mastery",                    icon: "🐱" },
  { universe: "DC", name: "Big Barda",        alias: "Barda Free",                   power: "New God strength & Mega-Rod",                        icon: "⚔" },
  { universe: "DC", name: "Mera",             alias: "Queen of Atlantis",            power: "Hydrokinesis & Atlantean strength",                  icon: "🌊" },
  { universe: "DC", name: "Vixen",            alias: "Mari Jiwe McCabe",             power: "Animal totem power mimicry",                         icon: "🦊" },
  { universe: "DC", name: "Stargirl",         alias: "Courtney Whitmore",            power: "Cosmic Staff & Cosmic Converter Belt",               icon: "⭐" },
  { universe: "DC", name: "Donna Troy",       alias: "Troia / Wonder Girl",          power: "Amazon strength & cosmic origin",                    icon: "💫" },
  { universe: "DC", name: "Jade",             alias: "Jennie-Lynn Hayden",           power: "Green energy constructs (GL power)",                 icon: "💚" },
  { universe: "DC", name: "Jessica Cruz",     alias: "Green Lantern",                power: "Willpower ring & construct creation",                 icon: "💍" },
  { universe: "DC", name: "Fire",             alias: "Beatriz da Costa",             power: "Green fire generation & flight",                     icon: "🔥" },
  { universe: "DC", name: "Ice",              alias: "Tora Olafsdotter",             power: "Ice generation & cryokinesis",                       icon: "❄" },
  { universe: "DC", name: "Mary Marvel",      alias: "Mary Bromfield",               power: "SHAZAM divine power set",                            icon: "⚡" },
  { universe: "DC", name: "Saturn Girl",      alias: "Imra Ardeen",                  power: "Powerful telepathy & mind control",                  icon: "🔮" },
  { universe: "DC", name: "Phantom Girl",     alias: "Tinya Wazzo",                  power: "Intangibility & phasing",                            icon: "👻" },
  { universe: "DC", name: "Dawnstar",         alias: "Dawnstar",                     power: "Tracking & interstellar flight",                     icon: "🌠" },
  { universe: "DC", name: "Dream Girl",       alias: "Nura Nal",                     power: "Precognitive dreams",                                icon: "🌙" },
  { universe: "DC", name: "Katana",           alias: "Tatsu Yamashiro",              power: "Soultaker sword & martial artist",                   icon: "⚔" },
  { universe: "DC", name: "Amethyst",         alias: "Amaya of House Amethyst",      power: "Gem magic & sorcery",                                icon: "💜" },
  { universe: "DC", name: "Soranik Natu",     alias: "Green Lantern II",             power: "Ring constructs & surgeon skills",                   icon: "💍" },
  { universe: "DC", name: "Thunder",          alias: "Anissa Pierce",                power: "Density control & shock waves",                      icon: "⚡" },
  { universe: "DC", name: "Lightning",        alias: "Jennifer Pierce",              power: "Lightning generation & control",                     icon: "🌩" },
  { universe: "DC", name: "Steel",            alias: "Natasha Irons",                power: "Powered armor & super-strength",                     icon: "🔩" },
  { universe: "DC", name: "Terra",            alias: "Tara Markov",                  power: "Geokinesis & earth manipulation",                    icon: "🌍" },
  { universe: "DC", name: "Maxima",           alias: "Queen Maxima",                 power: "Almeracian superhuman powers",                       icon: "👑" },
  { universe: "DC", name: "Jesse Quick",      alias: "Liberty Belle",                power: "Speedster & sonic vibrations",                       icon: "⚡" },
  { universe: "DC", name: "Ravager",          alias: "Rose Wilson",                  power: "Precognition & master combatant",                    icon: "🗡" },
  { universe: "DC", name: "Manhunter",        alias: "Kate Spencer",                 power: "Enhanced strength & energy staff",                   icon: "⚖" },
  { universe: "DC", name: "Cassandra Cain",   alias: "Batgirl II",                   power: "Body language reading & martial arts",               icon: "🦇" },
  { universe: "DC", name: "Stephanie Brown",  alias: "Spoiler / Batgirl",            power: "Detective skills & martial arts",                    icon: "🟡" },
  { universe: "DC", name: "Poison Ivy",       alias: "Pamela Isley",                 power: "Plant control & toxin immunity",                     icon: "🌿" },
  { universe: "DC", name: "Harley Quinn",     alias: "Dr. Harleen Quinzel",          power: "Superhuman agility & unpredictability",              icon: "🃏" },
  { universe: "DC", name: "Renee Montoya",    alias: "The Question",                 power: "Detective & martial arts master",                    icon: "❓" },
  // ── CW / Arrowverse ──────────────────────────────────────────
  { universe: "CW", name: "Sara Lance",       alias: "White Canary",                 power: "League assassin & temporal agent",                   icon: "🕊" },
  { universe: "CW", name: "Laurel Lance",     alias: "Black Canary",                 power: "Canary Cry device & martial artist",                 icon: "🎵" },
  { universe: "CW", name: "Thea Queen",       alias: "Speedy / Red Arrow",           power: "Olympic archer & League-trained fighter",            icon: "🏹" },
  { universe: "CW", name: "Nyssa al Ghul",    alias: "Heir to the Demon",            power: "League of Assassins grandmaster",                    icon: "🗡" },
  { universe: "CW", name: "Dinah Drake",      alias: "Black Canary III",             power: "Metahuman Canary Cry & street fighter",              icon: "🎤" },
  { universe: "CW", name: "Emiko Queen",      alias: "Green Arrow II",               power: "Master archer & trained assassin",                   icon: "🟢" },
  { universe: "CW", name: "Iris West-Allen",  alias: "The Flash's Heart",            power: "Speed Force conduit & journalist hero",              icon: "⚡" },
  { universe: "CW", name: "Caitlin Snow",     alias: "Killer Frost",                 power: "Cryokinesis & frost generation",                     icon: "❄" },
  { universe: "CW", name: "Jesse Quick",      alias: "Speed Force Hero",             power: "Speedster & genius intellect",                       icon: "💛" },
  { universe: "CW", name: "Nora West-Allen",  alias: "XS",                           power: "Speedster from the future",                          icon: "⚡" },
  { universe: "CW", name: "Zari Tomaz",       alias: "Totem Bearer",                 power: "Air totem manipulation & hacking",                   icon: "💨" },
  { universe: "CW", name: "Ava Sharpe",       alias: "Time Bureau Director",         power: "Tactical genius & time agent",                       icon: "⌚" },
  { universe: "CW", name: "Charlie",          alias: "Clotho / Legend",              power: "Shapeshifting & fate manipulation",                  icon: "🎭" },
  { universe: "CW", name: "Alex Danvers",     alias: "DEO Director",                 power: "Tactical genius & power-suit combat",                icon: "🛡" },
  { universe: "CW", name: "Lena Luthor",      alias: "Luthor Corp CEO",              power: "Genius inventor & Nth metal tech",                   icon: "🔬" },
  { universe: "CW", name: "Nia Nal",          alias: "Dreamer",                      power: "Precognitive dreams & energy blasts",                icon: "🌙" },
  { universe: "CW", name: "M'gann M'orzz",    alias: "Miss Martian",                 power: "Martian shapeshifting & telepathy",                  icon: "🟢" },
  // ── The Boys ─────────────────────────────────────────────────
  { universe: "TB", name: "Starlight",        alias: "Annie January",                power: "Light energy blasts, flight & super strength",       icon: "✨" },
  { universe: "TB", name: "Queen Maeve",      alias: "The Warrior Queen",            power: "Superhuman strength & near-invulnerability",         icon: "⚔" },
  { universe: "TB", name: "Kimiko",           alias: "Kimiko Miyashiro",             power: "Superhuman strength & rapid regeneration",           icon: "🩸" },
  { universe: "TB", name: "Firecracker",      alias: "Sheryl Braxton",               power: "Incendiary blasts & explosive manipulation",         icon: "🔥" },
  { universe: "TB", name: "Sister Sage",      alias: "The Smartest Person",          power: "Superintelligence & neural manipulation",            icon: "🧠" },
  { universe: "TB", name: "Victoria Neuman",  alias: "The Nupe",                     power: "Psychic head-explosion & political influence",       icon: "💥" },
  // ── Power Rangers ────────────────────────────────────────────
  { universe: "PR", name: "Kimberly Hart",   alias: "Pink Mighty Morphin Ranger",    power: "Pterodactyl Dinozord & expert gymnastics",           icon: "🦅" },
  { universe: "PR", name: "Trini Kwan",      alias: "Yellow Mighty Morphin Ranger",  power: "Sabertooth Tiger Dinozord & martial arts mastery",   icon: "🐯" },
  { universe: "PR", name: "Kat Pallister",   alias: "Pink Zeo Ranger",               power: "Pink Zeo Crystal & enhanced feline agility",        icon: "🐱" },
  { universe: "PR", name: "Cassie Chan",     alias: "Pink Space Ranger",             power: "Pink Astro Morpher & Mega Voyager piloting",        icon: "🚀" },
  { universe: "PR", name: "Ashley Hammond",  alias: "Yellow Space Ranger",           power: "Yellow Space Power & mechanical engineering genius", icon: "⚡" },
  { universe: "PR", name: "Dana Mitchell",   alias: "Pink Lightspeed Ranger",        power: "Pink Lightspeed Morpher & combat medic skills",     icon: "🏥" },
  { universe: "PR", name: "Karone",          alias: "Pink Lost Galaxy Ranger",       power: "Pink Galaxy Power & redemption of Astronema",       icon: "💫" },
  { universe: "PR", name: "Tori Hanson",     alias: "Blue Wind Ranger",              power: "Blue Wind Morpher & water-based ninjutsu",          icon: "🌊" },
  { universe: "PR", name: "Z Delgado",       alias: "Yellow SPD Ranger",             power: "Yellow SPD Morpher & biomolecular replication",     icon: "🔬" },
  { universe: "PR", name: "Syd Drew",        alias: "Pink SPD Ranger",               power: "Pink SPD Morpher & matter-density manipulation",    icon: "💎" },
  { universe: "PR", name: "Emma Goodall",    alias: "Pink Megaforce Ranger",         power: "Phoenix Zord & nature-based Megaforce powers",      icon: "🦋" },
  { universe: "PR", name: "Shelby Watkins",  alias: "Pink Dino Charge Ranger",       power: "Pink Dino Charge Morpher & Triceratops summoning",  icon: "🦕" },
  { universe: "PR", name: "Aisha Campbell",  alias: "Yellow Mighty Morphin Ranger",  power: "Sabertooth Tiger Dinozord & fierce martial arts",   icon: "🐯" },
  { universe: "PR", name: "Jen Scotts",      alias: "Pink Time Force Ranger",        power: "Pink Time Force Morpher & temporal law enforcement",icon: "⏳" },
  { universe: "PR", name: "Katie Walker",    alias: "Yellow Time Force Ranger",      power: "Yellow Time Force Morpher & superhuman strength",   icon: "💪" },
  { universe: "PR", name: "Kendrix Morgan",  alias: "Pink Lost Galaxy Ranger",       power: "Pink Quasar Saber & selfless cosmic sacrifice",     icon: "🌟" },
  { universe: "PR", name: "Maya",            alias: "Yellow Lost Galaxy Ranger",     power: "Yellow Quasar Saber & primal jungle instincts",     icon: "🌿" },
  { universe: "PR", name: "Vida Rocca",      alias: "Pink Mystic Force Ranger",      power: "Pink Mystic Morpher & magical wind transformation", icon: "🌸" },
  { universe: "PR", name: "Madison Rocca",   alias: "Blue Mystic Force Ranger",      power: "Blue Mystic Morpher & water elemental sorcery",     icon: "💧" },
  { universe: "PR", name: "Summer Landsdown",alias: "Yellow RPM Ranger",             power: "Yellow RPM Morpher & desert combat expertise",      icon: "☀" },
  { universe: "PR", name: "Gemma",           alias: "Silver RPM Ranger",             power: "Silver RPM Morpher & Cloud Hatchet twin-blade",     icon: "⚔" },
  { universe: "PR", name: "Mia Watanabe",    alias: "Pink Samurai Ranger",           power: "Sky Symbol Power & Sky Fan Folding Zord",           icon: "🌸" },
  { universe: "PR", name: "Emily",           alias: "Yellow Samurai Ranger",         power: "Earth Symbol Power & Earth Slicer disc weapon",     icon: "🌍" },
  { universe: "PR", name: "Gia Moran",       alias: "Yellow Megaforce Ranger",       power: "Tiger Zord & Super Megaforce combat mastery",       icon: "🐅" },
  { universe: "PR", name: "Kendall Morgan",  alias: "Purple Dino Charge Ranger",     power: "Purple Energem & Plesio Zord creation genius",     icon: "🔮" },
  { universe: "PR", name: "Amelia Jones",    alias: "Pink Dino Fury Ranger",         power: "Pink Dino Fury Morpher & Electro Zord channeling",  icon: "⚡" },
  { universe: "PR", name: "Izzy Garcia",     alias: "Green Dino Fury Ranger",        power: "Green Dino Fury Morpher & Mosa Razor Zord control", icon: "🌿" },
  // ── Animated ─────────────────────────────────────────────────
  { universe: "Animated", name: "Elsa",        alias: "Queen of Arendelle",          power: "Absolute cryokinesis & glacial fortresses",          icon: "❄" },
  { universe: "Animated", name: "Anna",         alias: "Princess of Arendelle",       power: "Act of true love magic & fearless tenacity",         icon: "💖" },
  { universe: "Animated", name: "Rapunzel",     alias: "Lost Princess of Corona",     power: "Enchanted hair, healing light & painting magic",     icon: "🌸" },
  { universe: "Animated", name: "Tiana",        alias: "Princess of the Bayou",       power: "Indomitable willpower & voodoo-touched resilience",  icon: "🐸" },
  { universe: "Animated", name: "Pocahontas",   alias: "Daughter of Chief Powhatan",  power: "Nature communion & spirit foresight",               icon: "🍃" },
  { universe: "Animated", name: "Megara",       alias: "Meg — Former Servant of Hades",power: "Razor wit & manipulative genius",                  icon: "🏛" },
  { universe: "Animated", name: "Esmeralda",    alias: "La Esmeralda — Gypsy",        power: "Master acrobat & mesmerising fighter",               icon: "🔥" },
  { universe: "Animated", name: "Jane",         alias: "Dr. Jane Porter",             power: "Scientific brilliance & primate language fluency",   icon: "🌿" },
  { universe: "Animated", name: "Kida",         alias: "Queen of Atlantis",           power: "Ancient crystal power & millennia of warrior training",icon: "💎" },
  { universe: "Animated", name: "Cinderella",   alias: "Princess of the Kingdom",     power: "Enchanted resilience — magic finds her",             icon: "👑" },
  { universe: "Animated", name: "Mulan",        alias: "Fa Mulan — Warrior of China", power: "Strategic genius & expert swordsmanship",            icon: "⚔" },
  { universe: "Animated", name: "Nani",         alias: "Nani Pelekai — Protector",    power: "Exceptional athleticism & fierce maternal fury",      icon: "🌊" },
  { universe: "Animated", name: "Belle",        alias: "Belle — Beauty",              power: "Intellectual mastery & enchanted castle access",      icon: "📖" },
  { universe: "Animated", name: "Isabela",      alias: "Isabela Madrigal",            power: "Full flora manipulation — flowers, thorns & vines",  icon: "🌺" },
  { universe: "Animated", name: "Kim Possible", alias: "Kim Possible — Teen Hero",    power: "Elite martial artist, gymnast & mission leader",     icon: "🎯" },
  { universe: "Animated", name: "Sam",          alias: "Sam — WOOHP Alpha Agent",     power: "Strategic genius & advanced spy gadgetry",           icon: "📋" },
  { universe: "Animated", name: "Clover",       alias: "Clover — WOOHP Style Agent",  power: "Elite acrobat & fashion-tech gadgets",               icon: "💋" },
  { universe: "Animated", name: "Alex",         alias: "Alex — WOOHP Field Agent",    power: "Peak athletic performance & gadget mastery",         icon: "⚡" },
  { universe: "Animated", name: "Helen Parr",   alias: "Elastigirl — Mrs Incredible", power: "Full-body elasticity up to 100 metres",              icon: "🔴" },
  { universe: "Animated", name: "Adora",        alias: "She-Ra — Princess of Power",  power: "Divine She-Ra transformation & Olympian strength",   icon: "⚔" },
  { universe: "Animated", name: "Harley Quinn", alias: "Dr. Harleen Quinzel — Chaos", power: "Enhanced physiology & psychological unpredictability",icon: "🃏" },
  { universe: "Animated", name: "Cheetara",     alias: "Cheetara — ThunderCat Cleric",power: "Superhuman speed & precognitive sight flashes",      icon: "🐆" },
  { universe: "Animated", name: "April O'Neil", alias: "April O'Neil — Kunoichi",     power: "Investigative journalist & developing kunoichi skills",icon: "📰" },
  { universe: "Animated", name: "Daphne Blake", alias: "Daphne — Mystery Incorporated",power: "Expert martial artist & supernatural magnet",       icon: "💜" },
  { universe: "Animated", name: "Asami Sato",   alias: "Future Industries CEO",        power: "Peak non-bender combatant & engineering genius",    icon: "⚡" },
  { universe: "Animated", name: "Korra",        alias: "Avatar Korra",                power: "Full Avatar mastery of all four elements",           icon: "🌊" },
  // ── Star Wars ────────────────────────────────────────────────
  { universe: "SW", name: "Padmé Amidala",  alias: "Senator & Former Queen of Naboo", power: "Political strategist & skilled markswoman",         icon: "👑" },
  { universe: "SW", name: "Leia Organa",    alias: "Princess — Senator — General",    power: "Gifted Force-sensitive & exceptional strategist",    icon: "⭐" },
  { universe: "SW", name: "Rey",            alias: "Rey Skywalker — Last Jedi",        power: "Force prodigy — telekinesis, healing & dyad bond",  icon: "⚔" },
  { universe: "SW", name: "Ahsoka Tano",    alias: "The Daughter — Rebel Agent",       power: "Dual white lightsabers & apex Jedi combat mastery", icon: "⚔" },
  { universe: "SW", name: "Jyn Erso",       alias: "Jyn Erso — Rogue One",             power: "Guerrilla combat & infiltration specialist",        icon: "🔫" },
  { universe: "SW", name: "Sabine Wren",    alias: "Mandalorian Artist",               power: "Mandalorian warrior, Darksaber & explosives genius", icon: "💣" },
  { universe: "SW", name: "Hera Syndulla",  alias: "General — Rebel Command",          power: "Finest pilot in the Rebellion & tactical genius",   icon: "🚀" },
  { universe: "SW", name: "Bo-Katan Kryze", alias: "Nite Owl Commander",               power: "Elite Mandalorian warrior & Darksaber claimant",    icon: "🗡" },
  { universe: "SW", name: "Asajj Ventress", alias: "Former Sith Assassin",             power: "Ferocious dark side Force & twin red lightsabers",  icon: "🔴" },
  { universe: "SW", name: "Aayla Secura",   alias: "Jedi Knight",                      power: "Extraordinary Force agility & dual lightsaber combat",icon: "💙" },
  { universe: "SW", name: "Qi'ra",          alias: "Crimson Dawn Underlord",            power: "Teräs Käsi master & underworld strategist",         icon: "💀" },
  { universe: "SW", name: "Fennec Shand",   alias: "Elite Assassin",                   power: "Galaxy's finest sniper & cold-blooded precision",   icon: "🎯" },
  { universe: "SW", name: "Mara Jade",      alias: "Emperor's Hand",                   power: "Force assassin with Jedi-grade telekinesis",        icon: "🟢" },
  // ── TV Live-Action ───────────────────────────────────────────
  { universe: "TV", name: "Lucy Chen",          alias: "Officer Chen — LAPD Metro",    power: "Undercover specialist & psychological warfare",      icon: "🚔" },
  { universe: "TV", name: "Sarah Walker",       alias: "Agent Walker — CIA/NSA",       power: "World-class martial artist & deep-cover specialist", icon: "🔫" },
  { universe: "TV", name: "Sydney Bristow",     alias: "Agent Bristow — CIA",          power: "Master of disguise & eight-language polyglot",      icon: "🎭" },
  { universe: "TV", name: "Irina Derevko",      alias: "The Man — KGB",                power: "Global criminal empire through ruthless brilliance", icon: "🕵️" },
  { universe: "TV", name: "Nikita",             alias: "Rogue Division Operative",      power: "Division's own creation turned against it",         icon: "⚡" },
  { universe: "TV", name: "Olivia Dunham",      alias: "Agent Dunham — Fringe",        power: "Cortexiphan-enhanced pyrokinesis & crossover ability",icon: "🔬" },
  { universe: "TV", name: "Prue Halliwell",     alias: "Most Powerful Charmed One",    power: "Telekinesis at master level & astral projection",   icon: "🌬️" },
  { universe: "TV", name: "Piper Halliwell",    alias: "Charmed One & Elder",          power: "Molecular immobilization & molecular combustion",   icon: "💧" },
  { universe: "TV", name: "River Tam",          alias: "Academy Super-Weapon",          power: "Psychic super-weapon with precognitive combat awareness",icon: "🧠" },
  { universe: "TV", name: "Max Guevara",        alias: "X5-452 Transgenic Soldier",    power: "Genetically engineered feline-DNA supersoldier",    icon: "🐈" },
  { universe: "TV", name: "Fiona Glenanne",     alias: "Former IRA Operative",          power: "Master bomb-maker & explosives architect",          icon: "💣" },
  { universe: "TV", name: "Carrie Mathison",    alias: "CIA Operations Officer",        power: "Unrivalled pattern-recognition & moral ruthlessness",icon: "🧩" },
  { universe: "TV", name: "Olivia Pope",        alias: "Washington DC's Top Fixer",    power: "Crisis manager who buried government-toppling scandals",icon: "🍷" },
  { universe: "TV", name: "Elizabeth Jennings", alias: "KGB Deep Cover",               power: "Elite combat, unmatched tradecraft & 15 years of perfect cover",icon: "🇷🇺" },
  { universe: "TV", name: "Root",               alias: "The Machine's Interface",       power: "Real-time intelligence, hacking & lethal unpredictability",icon: "🤖" },
  { universe: "TV", name: "Donna Paulsen",      alias: "Pearson Specter COO",           power: "Reads every person & room with supernatural accuracy",icon: "👠" },
  { universe: "TV", name: "Lana Lang",          alias: "Smallville Survivor",           power: "Martial arts master with kryptonite-powered suit",   icon: "💗" },
  { universe: "TV", name: "Chloe Sullivan",     alias: "Watchtower Intelligence",       power: "Justice League eyes & voice — Level 8 systems access",icon: "📡" },
  { universe: "TV", name: "Annie Walker",       alias: "CIA Field Operative",           power: "Linguist, martial artist & field improviser",        icon: "🌍" },
  { universe: "TV", name: "Bailey Nune",        alias: "Detective Nune — LAPD",         power: "Crisis negotiator & tactical firearms expert",       icon: "🔵" },
  { universe: "TV", name: "Veronica Mars",      alias: "Mars Investigations",           power: "Master investigator & tech-savvy surveillance ace",  icon: "🔍" },
  { universe: "TV", name: "Elena Michaels",     alias: "The Only Female Werewolf",      power: "Apex predator shapeshifter & Pack enforcer",         icon: "🐺" },
  { universe: "TV", name: "Teresa Lisbon",      alias: "Senior Agent — FBI",            power: "Unerring moral compass & interrogation master",      icon: "🟢" },
  { universe: "TV", name: "Rosa Diaz",          alias: "Detective Diaz — NYPD",         power: "Intimidation expert & hand-to-hand specialist",      icon: "🖤" },
  { universe: "TV", name: "Kono Kalakaua",      alias: "Five-0 Task Force",             power: "Surfer-bred athleticism & undercover master",        icon: "🌊" },
  { universe: "TV", name: "Maeve Millay",       alias: "Westworld Host — Awakened",     power: "Consciousness beyond programming & Host control",    icon: "🤍" },
  { universe: "TV", name: "Dana Scully",        alias: "Special Agent — FBI X-Files",   power: "Forensic pathologist & battle-tested field agent",   icon: "🔬" },
  { universe: "TV", name: "Grace Van Pelt",     alias: "Agent Van Pelt — CBI",          power: "Tech analyst, sharpshooter & psychological insight", icon: "🏹" },
  { universe: "TV", name: "Paige Dineen",      alias: "Team Scorpion Liaison",          power: "Behavioral specialist & human interface for genius",  icon: "🧠" },
];

export const HEROINE_UNIVERSES = ["Marvel", "DC", "CW", "TB", "PR", "Animated", "SW", "TV"] as const;
export type HeroineUniverse = typeof HEROINE_UNIVERSES[number];

export const UNIVERSE_LABELS: Record<string, string> = {
  Marvel: "Marvel",
  DC: "DC",
  CW: "Arrowverse",
  TB: "The Boys",
  PR: "Power Rangers",
  Animated: "Animated",
  SW: "Star Wars",
  TV: "TV Live-Action",
};
