export interface Villain {
  name: string;
  universe: string;
  scheme: string;
  icon: string;
}

export const VILLAINS: Villain[] = [
  // Marvel
  { name: "Thanos",              universe: "Marvel", scheme: "Wield cosmic power to reshape reality",                                                              icon: "💀" },
  { name: "Doctor Doom",         universe: "Marvel", scheme: "Rule the world through dark science",                                                               icon: "🤖" },
  { name: "Magneto",             universe: "Marvel", scheme: "Forge a world where mutants rule",                                                                  icon: "🧲" },
  { name: "Loki",                universe: "Marvel", scheme: "Claim the throne through divine trickery",                                                          icon: "🐍" },
  { name: "Ultron",              universe: "Marvel", scheme: "Eliminate organic life for machine order",                                                          icon: "⚙" },
  { name: "Kang the Conqueror",  universe: "Marvel", scheme: "Dominate the entire timeline",                                                                      icon: "⏳" },
  { name: "Galactus",            universe: "Marvel", scheme: "Devour worlds to sustain his existence",                                                            icon: "🌌" },
  { name: "Apocalypse",          universe: "Marvel", scheme: "Cull the weak and crown mutant supremacy",                                                          icon: "☠" },
  { name: "Mephisto",            universe: "Marvel", scheme: "Collect souls through damned bargains",                                                             icon: "😈" },
  { name: "Red Skull",           universe: "Marvel", scheme: "Forge a fascist world empire",                                                                      icon: "💀" },
  { name: "Dormammu",            universe: "Marvel", scheme: "Merge Earth with the Dark Dimension",                                                               icon: "🌀" },
  { name: "Baron Zemo",          universe: "Marvel", scheme: "Dismantle every hero institution",                                                                  icon: "🗡" },
  { name: "MODOK",               universe: "Marvel", scheme: "Rule through superior mechanical intellect",                                                        icon: "🧠" },
  { name: "Green Goblin",        universe: "Marvel", scheme: "Destroy Spider-Man through psychological war",                                                      icon: "🎃" },
  { name: "Venom / Carnage",     universe: "Marvel", scheme: "Unleash symbiote chaos on the world",                                                               icon: "🖤" },
  { name: "Hela",                universe: "Marvel", scheme: "Seize Asgard and expand her death domain",                                                         icon: "💀" },
  { name: "Lady Deathstrike",    universe: "Marvel", scheme: "Destroy Wolverine and claim mutant dominance",                                                     icon: "🗡" },
  { name: "Mystique",            universe: "Marvel", scheme: "Infiltrate and destabilize mutant enemies",                                                        icon: "🔵" },
  { name: "Morgan le Fay",       universe: "Marvel", scheme: "Rewrite reality with Arthurian dark sorcery",                                                      icon: "🔮" },
  { name: "The Enchantress",     universe: "Marvel", scheme: "Enslave heroes through magical seduction",                                                         icon: "💚" },
  { name: "Kingpin",             universe: "Marvel", scheme: "Build a criminal empire through iron will and ruthless business",                                   icon: "🏛" },
  { name: "Taskmaster",          universe: "Marvel", scheme: "Mirror any hero's technique and sell that advantage to enemies",                                    icon: "🎭" },
  { name: "Bullseye",            universe: "Marvel", scheme: "Make any object a lethal weapon and never miss the mark",                                           icon: "🎯" },
  { name: "Purple Man",          universe: "Marvel", scheme: "Bend any mind to absolute obedience through pheromone control",                                    icon: "🟣" },
  { name: "Malekith",            universe: "Marvel", scheme: "Plunge all Nine Realms into eternal darkness for the Dark Elves",                                  icon: "🌑" },
  { name: "Gorr the God Butcher",universe: "Marvel", scheme: "Hunt and exterminate every god across every timeline",                                              icon: "⚔" },
  { name: "Madame Hydra",        universe: "Marvel", scheme: "Spread HYDRA's serpentine dominion from the shadows",                                              icon: "🐍" },
  { name: "Abomination",         universe: "Marvel", scheme: "Surpass the Hulk and crush all resistance in his path",                                            icon: "💀" },
  { name: "Namor",               universe: "Marvel", scheme: "Force the surface world to bow to Atlantean supremacy",                                            icon: "🌊" },
  { name: "Cassandra Nova",      universe: "Marvel", scheme: "Destroy the Xavier legacy from within using his own power",                                        icon: "🔮" },
  { name: "Crossbones",          universe: "Marvel", scheme: "Carry out Hydra's bloodiest wetwork and topple Captain America's legacy",                          icon: "💀" },
  { name: "Whiplash",            universe: "Marvel", scheme: "Weaponise arc-reactor tech to destroy the Stark empire and legacy",                                icon: "⚡" },
  // DC
  { name: "Darkseid",            universe: "DC",     scheme: "Discover the Anti-Life Equation",                                                                  icon: "💥" },
  { name: "Lex Luthor",          universe: "DC",     scheme: "Prove humanity's superiority over gods",                                                            icon: "💰" },
  { name: "The Joker",           universe: "DC",     scheme: "Burn civilization into beautiful chaos",                                                            icon: "🃏" },
  { name: "Brainiac",            universe: "DC",     scheme: "Collect and miniaturize entire civilizations",                                                     icon: "🤖" },
  { name: "General Zod",         universe: "DC",     scheme: "Rebuild Krypton through conquest of Earth",                                                        icon: "☀" },
  { name: "Doomsday",            universe: "DC",     scheme: "Destroy all life through pure adaptive rage",                                                      icon: "💪" },
  { name: "Ra's al Ghul",        universe: "DC",     scheme: "Purge humanity to restore ecological balance",                                                     icon: "🌿" },
  { name: "Sinestro",            universe: "DC",     scheme: "Impose order through fear-based control",                                                          icon: "💛" },
  { name: "Cheetah",             universe: "DC",     scheme: "Destroy Wonder Woman and claim divine power",                                                      icon: "🐆" },
  { name: "Circe",               universe: "DC",     scheme: "Wage divine war against all of humanity",                                                          icon: "🔮" },
  { name: "Trigon",              universe: "DC",     scheme: "Consume Earth as another conquered realm",                                                         icon: "😈" },
  { name: "Black Manta",         universe: "DC",     scheme: "Destroy Atlantis and Aquaman's legacy",                                                            icon: "🔱" },
  { name: "Reverse-Flash",       universe: "DC",     scheme: "Shatter the Flash's life across time",                                                             icon: "⚡" },
  { name: "Vandal Savage",       universe: "DC",     scheme: "Rule the world as its immortal king",                                                              icon: "🗡" },
  { name: "Deathstroke",         universe: "DC",     scheme: "Complete any contract with absolute precision",                                                    icon: "⚔" },
  { name: "Black Adam",          universe: "DC",     scheme: "Reclaim Kahndaq and punish the unworthy",                                                         icon: "⚡" },
  { name: "Amanda Waller",       universe: "DC",     scheme: "Control metahumans as weapons for the state",                                                     icon: "🏛" },
  { name: "Granny Goodness",     universe: "DC",     scheme: "Break heroes through endless torment",                                                             icon: "👵" },
  { name: "Bane",                universe: "DC",     scheme: "Break Batman and seize Gotham as his conquered throne",                                            icon: "💪" },
  { name: "Scarecrow",           universe: "DC",     scheme: "Drown the world in its own paralyzing fear and madness",                                           icon: "🌾" },
  { name: "The Riddler",         universe: "DC",     scheme: "Prove superior intellect by destroying the greatest minds in Gotham",                              icon: "❓" },
  { name: "Anti-Monitor",        universe: "DC",     scheme: "Annihilate the positive matter multiverse and replace it with anti-matter",                        icon: "💥" },
  { name: "Parasite",            universe: "DC",     scheme: "Drain every hero's power and become an unstoppable living god",                                    icon: "🟣" },
  { name: "Giganta",             universe: "DC",     scheme: "Crush obstacles at towering height and claim what she desires",                                    icon: "⬆" },
  { name: "Queen of Fables",     universe: "DC",     scheme: "Rewrite reality as her dark fairy tale kingdom of terror",                                        icon: "📖" },
  { name: "Ocean Master",        universe: "DC",     scheme: "Declare war on the surface world in Atlantis's name",                                              icon: "🔱" },
  { name: "Mr. Freeze",          universe: "DC",     scheme: "Freeze Gotham and hold it ransom until his wife Nora can be saved",                               icon: "❄️" },
  { name: "Hush",                universe: "DC",     scheme: "Dismantle every relationship Batman holds dear and expose his secret",                             icon: "🤐" },
  // CW / Arrowverse
  { name: "Malcolm Merlyn",      universe: "CW",     scheme: "Destroy the Glades to purge Star City of sin",                                                    icon: "🏹" },
  { name: "Damien Darhk",        universe: "CW",     scheme: "Embrace Hive's death magic to raze the world",                                                   icon: "💀" },
  { name: "Prometheus",          universe: "CW",     scheme: "Break the Green Arrow by destroying everything he loves",                                          icon: "🎯" },
  { name: "Ricardo Diaz",        universe: "CW",     scheme: "Own an entire city through crime and corruption",                                                  icon: "🐉" },
  { name: "Zoom",                universe: "CW",     scheme: "Steal every speedster's speed and rule all Earths",                                                icon: "⚡" },
  { name: "Savitar",             universe: "CW",     scheme: "Become a god of speed by eliminating rivals",                                                     icon: "⚡" },
  { name: "Gorilla Grodd",       universe: "CW",     scheme: "Build a telepathic ape empire over humanity",                                                     icon: "🦍" },
  { name: "The Thinker",         universe: "CW",     scheme: "Absorb all metahuman powers to control the world",                                                icon: "🧠" },
  { name: "Eva McCulloch",       universe: "CW",     scheme: "Replace the real world with her mirror dimension",                                                 icon: "🪞" },
  { name: "Reign",               universe: "CW",     scheme: "Purge Earth of sin as World Killer",                                                              icon: "☀" },
  { name: "Non",                 universe: "CW",     scheme: "Mind-control all humans into subservience",                                                       icon: "🌀" },
  { name: "Agent Liberty",       universe: "CW",     scheme: "Incite humanity to exterminate metahumans",                                                       icon: "🗽" },
  { name: "Mallus",              universe: "CW",     scheme: "Break free of his prison and devour all time",                                                    icon: "😈" },
  { name: "Cicada",              universe: "CW",     scheme: "Systematically hunt and kill every metahuman alive on Earth",                                     icon: "🪲" },
  { name: "Bloodwork",           universe: "CW",     scheme: "Weaponise blood control to achieve biological immortality",                                       icon: "🩸" },
  { name: "Cayden James",        universe: "CW",     scheme: "Turn cyber-terrorism into world-ending leverage over Star City",                                  icon: "💻" },
  // The Boys
  { name: "Homelander",          universe: "TB",     scheme: "Maintain iron control over Vought and all supes",                                                 icon: "🔴" },
  { name: "Stormfront",          universe: "TB",     scheme: "Weaponize supes for ideological supremacy",                                                       icon: "⚡" },
  { name: "Soldier Boy",         universe: "TB",     scheme: "Reclaim relevance through ruthless retribution",                                                  icon: "🛡" },
  { name: "The Deep",            universe: "TB",     scheme: "Claw back standing in The Seven by any means",                                                    icon: "🌊" },
  { name: "A-Train",             universe: "TB",     scheme: "Outrun his past and stay relevant at any cost",                                                   icon: "💨" },
  { name: "Black Noir",          universe: "TB",     scheme: "Carry out Vought's kill-orders without hesitation",                                               icon: "🖤" },
  { name: "Translucent",         universe: "TB",     scheme: "Infiltrate and expose enemies from the shadows",                                                  icon: "👁" },
  { name: "Lamplighter",         universe: "TB",     scheme: "Burn any loose end Vought orders him to eliminate",                                               icon: "🔥" },
  { name: "Crimson Countess",    universe: "TB",     scheme: "Exploit celebrity supe fame while hiding Payback's darkest atrocities",                           icon: "❤" },
  { name: "Blue Hawk",           universe: "TB",     scheme: "Use Vought backing to enforce brutal vigilante justice with zero accountability",                  icon: "🦅" },
  { name: "Gunpowder",           universe: "TB",     scheme: "Leverage gun-based powers and political connections to serve Vought's agenda",                    icon: "🔫" },
  // Power Rangers
  { name: "Rita Repulsa",        universe: "PR",     scheme: "Conquer Earth and destroy the Power Rangers once and for all",                                    icon: "🧙" },
  { name: "Lord Zedd",           universe: "PR",     scheme: "Reclaim dominion as Emperor of Evil across the entire universe",                                  icon: "👑" },
  { name: "Thrax",               universe: "PR",     scheme: "Unite all villains to destroy Sentinel Knight and avenge his parents' defeat",                    icon: "⚔" },
  { name: "Dark Specter",        universe: "PR",     scheme: "Drain Zordon's power and conquer the entire universe as Grand Monarch",                           icon: "🌑" },
  { name: "Astronema",           universe: "PR",     scheme: "Serve Dark Specter and obliterate the Space Rangers utterly",                                     icon: "🌑" },
  { name: "Divatox",             universe: "PR",     scheme: "Plunder the galaxy and eliminate Zordon's lasting legacy",                                        icon: "🏴‍☠️" },
  { name: "Scorpius",            universe: "PR",     scheme: "Gather the Quasar Sabers to achieve ultimate power over the galaxy",                              icon: "🦂" },
  { name: "Trakeena",            universe: "PR",     scheme: "Destroy everything Kendrix Morgan sacrificed herself to protect",                                 icon: "🦂" },
  { name: "Ransik",              universe: "PR",     scheme: "Dominate the past and reshape the future entirely for mutantkind",                                icon: "🧬" },
  { name: "Master Org",          universe: "PR",     scheme: "Exterminate humanity and restore Orgs as rulers of the Wild Force world",                        icon: "🌿" },
  { name: "Lothor",              universe: "PR",     scheme: "Collect enough ninja souls to open the Abyss of Evil and conquer Earth",                          icon: "🌀" },
  { name: "Mesogog",             universe: "PR",     scheme: "De-evolve humanity back to the prehistoric age of dinosaurs",                                     icon: "🦖" },
  { name: "Gruumm",              universe: "PR",     scheme: "Conquer Earth for the Troobian Empire and feed the Magnificence",                                 icon: "💀" },
  { name: "Venjix",              universe: "PR",     scheme: "Wipe out the last of humanity and absorb all computer systems as one",                            icon: "🤖" },
  { name: "Master Xandred",      universe: "PR",     scheme: "Flood the Sanzu River into the human world and rule it in darkness",                              icon: "🌊" },
  { name: "Vrak",                universe: "PR",     scheme: "Betray his own royal family to reshape Earth under Warstar dominion",                             icon: "👽" },
  { name: "Sledge",              universe: "PR",     scheme: "Collect every powerful Energem and sell them across the galaxy",                                  icon: "⛓" },
  { name: "Madame Odius",        universe: "PR",     scheme: "Steal ninja power through deception and claim the Ninja Nexus Prism",                             icon: "🎭" },
  { name: "Void Knight",         universe: "PR",     scheme: "Resurrect his beloved at any cost — even destroying the Dino Fury Rangers",                      icon: "🗡" },
  // Star Wars
  { name: "Darth Vader",         universe: "SW",     scheme: "Serve the Emperor and crush all Rebel resistance across the galaxy",                              icon: "⬛" },
  { name: "Emperor Palpatine",   universe: "SW",     scheme: "Rule the galaxy as God-Emperor through absolute Sith mastery",                                   icon: "👁" },
  { name: "Kylo Ren",            universe: "SW",     scheme: "Destroy the last Jedi and rule the galaxy as Supreme Leader",                                    icon: "🔴" },
  { name: "Count Dooku",         universe: "SW",     scheme: "Reshape galactic politics through Separatist war and Sith manipulation",                         icon: "⚡" },
  { name: "Darth Maul",          universe: "SW",     scheme: "Rebuild his criminal empire and destroy those who humiliated him",                                icon: "🔴" },
  { name: "Grand Admiral Thrawn",universe: "SW",     scheme: "Conquer the New Republic through tactical genius and cultural study",                             icon: "🎨" },
  { name: "Moff Gideon",         universe: "SW",     scheme: "Harness Mandalorian power and dark science to rebuild the Empire",                               icon: "⚔" },
  { name: "Director Krennic",    universe: "SW",     scheme: "Complete the Death Star and claim his place at the Emperor's side",                               icon: "💀" },
  { name: "Grand Moff Tarkin",   universe: "SW",     scheme: "Rule through fear — the Death Star is the ultimate demonstration",                                icon: "🏛" },
  { name: "Boba Fett",           universe: "SW",     scheme: "Complete any bounty contract and cement his legacy as the galaxy's greatest hunter",             icon: "🎯" },
  { name: "The Grand Inquisitor",universe: "SW",     scheme: "Hunt every surviving Jedi to extinction on the Emperor's order",                                 icon: "🔺" },
  { name: "Jabba the Hutt",      universe: "SW",     scheme: "Expand Hutt cartel dominion and collect every debt owed to him",                                 icon: "🐸" },
  { name: "General Grievous",    universe: "SW",     scheme: "Collect Jedi lightsabers as trophies while executing Separatist conquest",                       icon: "🤖" },
  { name: "Darth Revan",         universe: "SW",     scheme: "Forge an empire through the combined power of both light and dark side",                         icon: "🌑" },
  // Animated
  { name: "Maleficent",          universe: "Animated", scheme: "Curse every soul who defies her and blanket the Moors in eternal darkness",                   icon: "🌑" },
  { name: "Ursula",              universe: "Animated", scheme: "Collect desperate souls through impossible bargains and seize Triton's trident",               icon: "🐙" },
  { name: "Evil Queen",          universe: "Animated", scheme: "Destroy Snow White and reclaim the title of the fairest through dark sorcery",                icon: "🍎" },
  { name: "Mother Gothel",       universe: "Animated", scheme: "Keep Rapunzel imprisoned forever as a living source of youth and immortality",                icon: "🌸" },
  { name: "Cruella de Vil",      universe: "Animated", scheme: "Skin one hundred and one Dalmatian puppies to create the ultimate fur coat",                  icon: "💀" },
  { name: "Yzma",                universe: "Animated", scheme: "Assassinate Emperor Kuzco and seize the Incan Empire through scheming brilliance",             icon: "⚗" },
  { name: "Queen of Hearts",     universe: "Animated", scheme: "Maintain absolute terrifying rule through arbitrary decrees — off with their heads",           icon: "❤" },
];

export const VILLAIN_UNIVERSES = ["Marvel", "DC", "CW", "TB", "PR", "SW", "Animated"] as const;
export type VillainUniverse = typeof VILLAIN_UNIVERSES[number];
