export interface Villain {
  name: string;
  universe: string;
  scheme: string;
  icon: string;
}

export const VILLAINS: Villain[] = [
  // Marvel
  { name: "Thanos",              universe: "Marvel", scheme: "Wield cosmic power to reshape reality",                                                              icon: "💀" },
  { name: "Doctor Doom",         universe: "Marvel", scheme: "Rule the world through dark science",                                                               icon: "🤖" },
  { name: "Magneto",             universe: "Marvel", scheme: "Forge a world where mutants rule",                                                                  icon: "🧲" },
  { name: "Loki",                universe: "Marvel", scheme: "Claim the throne through divine trickery",                                                          icon: "🐍" },
  { name: "Ultron",              universe: "Marvel", scheme: "Eliminate organic life for machine order",                                                          icon: "⚙" },
  { name: "Kang the Conqueror",  universe: "Marvel", scheme: "Dominate the entire timeline",                                                                      icon: "⏳" },
  { name: "Galactus",            universe: "Marvel", scheme: "Devour worlds to sustain his existence",                                                            icon: "🌌" },
  { name: "Apocalypse",          universe: "Marvel", scheme: "Cull the weak and crown mutant supremacy",                                                          icon: "☠" },
  { name: "Mephisto",            universe: "Marvel", scheme: "Collect souls through damned bargains",                                                             icon: "😈" },
  { name: "Red Skull",           universe: "Marvel", scheme: "Forge a fascist world empire",                                                                      icon: "💀" },
  { name: "Dormammu",            universe: "Marvel", scheme: "Merge Earth with the Dark Dimension",                                                               icon: "🌀" },
  { name: "Baron Zemo",          universe: "Marvel", scheme: "Dismantle every hero institution",                                                                  icon: "🗡" },
  { name: "MODOK",               universe: "Marvel", scheme: "Rule through superior mechanical intellect",                                                        icon: "🧠" },
  { name: "Green Goblin",        universe: "Marvel", scheme: "Destroy Spider-Man through psychological war",                                                      icon: "🎃" },
  { name: "Venom / Carnage",     universe: "Marvel", scheme: "Unleash symbiote chaos on the world",                                                               icon: "🖤" },
  { name: "Hela",                universe: "Marvel", scheme: "Seize Asgard and expand her death domain",                                                         icon: "💀" },
  { name: "Lady Deathstrike",    universe: "Marvel", scheme: "Destroy Wolverine and claim mutant dominance",                                                     icon: "🗡" },
  { name: "Mystique",            universe: "Marvel", scheme: "Infiltrate and destabilize mutant enemies",                                                        icon: "🔵" },
  { name: "Morgan le Fay",       universe: "Marvel", scheme: "Rewrite reality with Arthurian dark sorcery",                                                      icon: "🔮" },
  { name: "The Enchantress",     universe: "Marvel", scheme: "Enslave heroes through magical seduction",                                                         icon: "💚" },
  { name: "Kingpin",             universe: "Marvel", scheme: "Build a criminal empire through iron will and ruthless business",                                   icon: "🏛" },
  { name: "Taskmaster",          universe: "Marvel", scheme: "Mirror any hero's technique and sell that advantage to enemies",                                    icon: "🎭" },
  { name: "Bullseye",            universe: "Marvel", scheme: "Make any object a lethal weapon and never miss the mark",                                           icon: "🎯" },
  { name: "Purple Man",          universe: "Marvel", scheme: "Bend any mind to absolute obedience through pheromone control",                                    icon: "🟣" },
  { name: "Malekith",            universe: "Marvel", scheme: "Plunge all Nine Realms into eternal darkness for the Dark Elves",                                  icon: "🌑" },
  { name: "Gorr the God Butcher",universe: "Marvel", scheme: "Hunt and exterminate every god across every timeline",                                              icon: "⚔" },
  { name: "Madame Hydra",        universe: "Marvel", scheme: "Spread HYDRA's serpentine dominion from the shadows",                                              icon: "🐍" },
  { name: "Abomination",         universe: "Marvel", scheme: "Surpass the Hulk and crush all resistance in his path",                                            icon: "💀" },
  { name: "Namor",               universe: "Marvel", scheme: "Force the surface world to bow to Atlantean supremacy",                                            icon: "🌊" },
  { name: "Cassandra Nova",      universe: "Marvel", scheme: "Destroy the Xavier legacy from within using his own power",                                        icon: "🔮" },
  { name: "Crossbones",          universe: "Marvel", scheme: "Carry out Hydra's bloodiest wetwork and topple Captain America's legacy",                          icon: "💀" },
  { name: "Whiplash",            universe: "Marvel", scheme: "Weaponise arc-reactor tech to destroy the Stark empire and legacy",                                icon: "⚡" },
  // Marvel Female Villains
  { name: "Typhoid Mary",        universe: "Marvel", scheme: "Burn the world with split-personality pyrokinetic chaos while Daredevil watches",                   icon: "🔥" },
  { name: "Madame Masque",       universe: "Marvel", scheme: "Rebuild the Nefaria criminal empire from behind her golden iron mask",                              icon: "🎭" },
  { name: "Viper",               universe: "Marvel", scheme: "Poison the world's power structures from within as HYDRA's supreme commander",                      icon: "🐍" },
  { name: "Titania",             universe: "Marvel", scheme: "Crush every hero who dares stand between her and absolute dominance",                               icon: "💪" },
  { name: "Moonstone",           universe: "Marvel", scheme: "Manipulate allies and enemies alike while her gravity stone makes her a god",                       icon: "🌙" },
  { name: "Selene",              universe: "Marvel", scheme: "Feed on souls for millennia until she ascends as the Black Queen of all mutantkind",                icon: "🩸" },
  { name: "Deathbird",           universe: "Marvel", scheme: "Tear the Shi'ar throne from her sister's grasp through savage conquest",                            icon: "🦅" },
  { name: "Spiral",              universe: "Marvel", scheme: "Trap heroes in the Body Shoppe and reshape them as her twisted magical creations",                  icon: "🌀" },
  { name: "Satana",              universe: "Marvel", scheme: "Devour the souls of the righteous and drag the living world into her father's hell",                icon: "😈" },
  { name: "Goblin Queen",        universe: "Marvel", scheme: "Tear reality apart as Madelyne Pryor — Jean Grey's clone — claims her dark throne",                icon: "👑" },
  { name: "Arclight",            universe: "Marvel", scheme: "Shatter everything and everyone in her path with concussive shockwave power",                       icon: "⚡" },
  { name: "Shriek",              universe: "Marvel", scheme: "Unleash sonic madness on the world alongside Carnage in a symphony of destruction",                 icon: "🔊" },
  { name: "Sin",                 universe: "Marvel", scheme: "Finish what her father Red Skull started and remake the world in fascist fire",                     icon: "💀" },
  { name: "Vertigo",             universe: "Marvel", scheme: "Disorient and incapacitate every hero who enters the Savage Land on her terms",                    icon: "💫" },
  { name: "Callisto",            universe: "Marvel", scheme: "Rule the Morlocks underground and make the surface world pay for every scar",                      icon: "🗡" },
  { name: "Lady Mastermind",     universe: "Marvel", scheme: "Shatter every hero's mind with hyper-realistic illusions they can never escape",                   icon: "🔮" },
  { name: "Superia",             universe: "Marvel", scheme: "Build a female supremacist empire on the ruins of every male-run institution",                     icon: "⚗" },
  { name: "Skein",               universe: "Marvel", scheme: "Unravel heroes with telekinetic control over any fibrous material",                                 icon: "🧵" },
  { name: "Snapdragon",          universe: "Marvel", scheme: "Hunt and eliminate targets with expert-mercenary precision and sadistic pleasure",                  icon: "🌺" },
  { name: "Nekra",               universe: "Marvel", scheme: "Feed on hatred itself to grow stronger and tear down every hero who pities her",                   icon: "🖤" },
  { name: "Proxima Midnight",    universe: "Marvel", scheme: "Annihilate every Avenger as Thanos's most feared Black Order general and conquering warlord",       icon: "🌑" },
  { name: "Shiklah",             universe: "Marvel", scheme: "Rule Monster Metropolis as its shapeshifting queen and drag the world of monsters into dominance",  icon: "👑" },
  { name: "Black Mamba",         universe: "Marvel", scheme: "Crush enemies in her psychic darkforce serpent's coils and profit handsomely doing it",             icon: "🐍" },
  { name: "Asp",                 universe: "Marvel", scheme: "Strike lethally with electro-venom blasts as a mercenary who answers only to the highest bidder",   icon: "⚡" },
  { name: "Malice",              universe: "Marvel", scheme: "Possess and corrupt heroines from within, turning their love and loyalty into a weapon against them",icon: "💜" },
  { name: "Man-Killer",          universe: "Marvel", scheme: "Dismantle every patriarchal power structure with superhuman force until men know true fear",         icon: "✊" },
  { name: "Scorpia",             universe: "Marvel", scheme: "Sting her way to the top of the criminal underworld as the female Scorpion who refuses to be second",icon: "🦂" },
  { name: "Princess Python",     universe: "Marvel", scheme: "Command her giant serpent and run rings around any hero foolish enough to underestimate the circus", icon: "🐍" },
  { name: "Dragoness",           universe: "Marvel", scheme: "Breathe fire and terror as the Mutant Liberation Front's most ferocious aerial combatant",          icon: "🔥" },
  { name: "Joystick",            universe: "Marvel", scheme: "Treat every fight as a game and collect the prize money from whichever side pays more",              icon: "🎮" },
  // DC
  { name: "Darkseid",            universe: "DC",     scheme: "Discover the Anti-Life Equation",                                                                  icon: "💥" },
  { name: "Lex Luthor",          universe: "DC",     scheme: "Prove humanity's superiority over gods",                                                            icon: "💰" },
  { name: "The Joker",           universe: "DC",     scheme: "Burn civilization into beautiful chaos",                                                            icon: "🃏" },
  { name: "Brainiac",            universe: "DC",     scheme: "Collect and miniaturize entire civilizations",                                                     icon: "🤖" },
  { name: "General Zod",         universe: "DC",     scheme: "Rebuild Krypton through conquest of Earth",                                                        icon: "☀" },
  { name: "Doomsday",            universe: "DC",     scheme: "Destroy all life through pure adaptive rage",                                                      icon: "💪" },
  { name: "Ra's al Ghul",        universe: "DC",     scheme: "Purge humanity to restore ecological balance",                                                     icon: "🌿" },
  { name: "Sinestro",            universe: "DC",     scheme: "Impose order through fear-based control",                                                          icon: "💛" },
  { name: "Cheetah",             universe: "DC",     scheme: "Destroy Wonder Woman and claim divine power",                                                      icon: "🐆" },
  { name: "Circe",               universe: "DC",     scheme: "Wage divine war against all of humanity",                                                          icon: "🔮" },
  { name: "Trigon",              universe: "DC",     scheme: "Consume Earth as another conquered realm",                                                         icon: "😈" },
  { name: "Black Manta",         universe: "DC",     scheme: "Destroy Atlantis and Aquaman's legacy",                                                            icon: "🔱" },
  { name: "Reverse-Flash",       universe: "DC",     scheme: "Shatter the Flash's life across time",                                                             icon: "⚡" },
  { name: "Vandal Savage",       universe: "DC",     scheme: "Rule the world as its immortal king",                                                              icon: "🗡" },
  { name: "Deathstroke",         universe: "DC",     scheme: "Complete any contract with absolute precision",                                                    icon: "⚔" },
  { name: "Black Adam",          universe: "DC",     scheme: "Reclaim Kahndaq and punish the unworthy",                                                         icon: "⚡" },
  { name: "Amanda Waller",       universe: "DC",     scheme: "Control metahumans as weapons for the state",                                                     icon: "🏛" },
  { name: "Granny Goodness",     universe: "DC",     scheme: "Break heroes through endless torment",                                                             icon: "👵" },
  { name: "Bane",                universe: "DC",     scheme: "Break Batman and seize Gotham as his conquered throne",                                            icon: "💪" },
  { name: "Scarecrow",           universe: "DC",     scheme: "Drown the world in its own paralyzing fear and madness",                                           icon: "🌾" },
  { name: "The Riddler",         universe: "DC",     scheme: "Prove superior intellect by destroying the greatest minds in Gotham",                              icon: "❓" },
  { name: "Anti-Monitor",        universe: "DC",     scheme: "Annihilate the positive matter multiverse and replace it with anti-matter",                        icon: "💥" },
  { name: "Parasite",            universe: "DC",     scheme: "Drain every hero's power and become an unstoppable living god",                                    icon: "🟣" },
  { name: "Giganta",             universe: "DC",     scheme: "Crush obstacles at towering height and claim what she desires",                                    icon: "⬆" },
  { name: "Queen of Fables",     universe: "DC",     scheme: "Rewrite reality as her dark fairy tale kingdom of terror",                                        icon: "📖" },
  { name: "Ocean Master",        universe: "DC",     scheme: "Declare war on the surface world in Atlantis's name",                                              icon: "🔱" },
  { name: "Mr. Freeze",          universe: "DC",     scheme: "Freeze Gotham and hold it ransom until his wife Nora can be saved",                               icon: "❄️" },
  { name: "Hush",                universe: "DC",     scheme: "Dismantle every relationship Batman holds dear and expose his secret",                             icon: "🤐" },
  // DC Female Villains
  { name: "Harley Quinn",        universe: "DC",     scheme: "Bring glorious anarchic madness to Gotham — on her own terms, no longer anyone's pawn",             icon: "🃏" },
  { name: "Poison Ivy",          universe: "DC",     scheme: "Exterminate humanity and restore Earth to the plants that deserve to inherit it",                    icon: "🌿" },
  { name: "Catwoman",            universe: "DC",     scheme: "Steal the most untouchable treasures in the world and vanish before justice even blinks",            icon: "🐈" },
  { name: "Killer Frost",        universe: "DC",     scheme: "Freeze the warmth out of every hero who ever made her feel like a monster",                          icon: "❄️" },
  { name: "Talia al Ghul",       universe: "DC",     scheme: "Position herself as the true heir to the League of Shadows by breaking Batman completely",           icon: "🗡" },
  { name: "Enchantress",         universe: "DC",     scheme: "Devour humanity's worship and reshape the world as an ancient sorceress who will never be caged",    icon: "🔮" },
  { name: "Black Siren",         universe: "DC",     scheme: "Destroy Earth-1's heroes as the Earth-2 Black Canary who has nothing left to lose",                  icon: "🔊" },
  { name: "Star Sapphire",       universe: "DC",     scheme: "Enslave Hal Jordan's heart and mind through the violet power of love turned weapon",                 icon: "💜" },
  { name: "Silver Banshee",      universe: "DC",     scheme: "Shriek the life from every enemy until she reclaims the mystical artifact stolen from her clan",     icon: "👻" },
  { name: "Maxima",              universe: "DC",     scheme: "Seize Superman as her consort and conquer Earth as her imperial breeding ground",                    icon: "👑" },
  { name: "Livewire",            universe: "DC",     scheme: "Short-circuit every hero who underestimates her and make Superman bleed electricity",               icon: "⚡" },
  { name: "Lady Shiva",          universe: "DC",     scheme: "Become the undisputed deadliest martial artist alive by defeating every warrior worth defeating",    icon: "🥋" },
  { name: "Ravager",             universe: "DC",     scheme: "Carve her own legend with twin blades, out of Deathstroke's shadow and into her own darkness",       icon: "⚔" },
  { name: "Superwoman",          universe: "DC",     scheme: "Rule Earth as the Crime Syndicate's Lois Lane, where power and cruelty are the only virtues",        icon: "☀" },
  { name: "Emerald Empress",     universe: "DC",     scheme: "Wield the Emerald Eye of Ekron to bend time and destroy the Legion of Super-Heroes",                icon: "👁" },
  { name: "Jinx",                universe: "DC",     scheme: "Curse every hero into misfortune until the world bows to bad luck made manifest",                    icon: "🌀" },
  { name: "Doctor Poison",       universe: "DC",     scheme: "Deploy devastating chemical weapons to destroy the civilisation that cast her out as a monster",      icon: "☠" },
  { name: "Volcana",             universe: "DC",     scheme: "Burn down every institution that imprisoned her and make Superman feel real heat for once",           icon: "🔥" },
  { name: "Scandal Savage",      universe: "DC",     scheme: "Survive anything — as Vandal Savage's daughter, death is merely inconvenient",                       icon: "🩸" },
  { name: "Bleez",               universe: "DC",     scheme: "Unleash Red Lantern rage on a universe that gave her only suffering in return for love",             icon: "🔴" },
  { name: "Blackfire",           universe: "DC",     scheme: "Seize the Tamaranean throne from her sister Starfire by any means of conquest and cruelty",         icon: "🔥" },
  { name: "Terra",               universe: "DC",     scheme: "Infiltrate the Teen Titans as a spy and destroy them from the inside for Deathstroke",               icon: "🪨" },
  { name: "Cheshire",            universe: "DC",     scheme: "Complete any assassination contract with poison-laced precision and vanish before vengeance arrives", icon: "🐱" },
  { name: "Lashina",             universe: "DC",     scheme: "Whip Apokolips's enemies into submission as one of Darkseid's deadliest Female Furies",              icon: "⛓" },
  { name: "Nyssa al Ghul",       universe: "DC",     scheme: "Rebuild the League of Assassins in her own ruthless image and surpass her father's legacy entirely", icon: "🗡" },
  { name: "Plastique",           universe: "DC",     scheme: "Detonate the foundations of every institution she despises with her explosive-generating power",      icon: "💥" },
  { name: "Queen Bee",           universe: "DC",     scheme: "Mind-control world leaders and heroes alike to install herself as Earth's supreme ruler",            icon: "🐝" },
  { name: "Mercy Graves",        universe: "DC",     scheme: "Protect Lex Luthor and eliminate every threat to his empire with android-enhanced lethality",        icon: "🤖" },
  { name: "Mad Harriet",         universe: "DC",     scheme: "Slash and claw through any obstacle as Apokolips's most gleefully violent Female Fury",              icon: "🔪" },
  { name: "Shado",               universe: "DC",     scheme: "Loose her arrows with ancient yakuza precision and vanish before her target hits the ground",        icon: "🏹" },
  // CW / Arrowverse
  { name: "Malcolm Merlyn",      universe: "CW",     scheme: "Destroy the Glades to purge Star City of sin",                                                    icon: "🏹" },
  { name: "Damien Darhk",        universe: "CW",     scheme: "Embrace Hive's death magic to raze the world",                                                   icon: "💀" },
  { name: "Prometheus",          universe: "CW",     scheme: "Break the Green Arrow by destroying everything he loves",                                          icon: "🎯" },
  { name: "Ricardo Diaz",        universe: "CW",     scheme: "Own an entire city through crime and corruption",                                                  icon: "🐉" },
  { name: "Zoom",                universe: "CW",     scheme: "Steal every speedster's speed and rule all Earths",                                                icon: "⚡" },
  { name: "Savitar",             universe: "CW",     scheme: "Become a god of speed by eliminating rivals",                                                     icon: "⚡" },
  { name: "Gorilla Grodd",       universe: "CW",     scheme: "Build a telepathic ape empire over humanity",                                                     icon: "🦍" },
  { name: "The Thinker",         universe: "CW",     scheme: "Absorb all metahuman powers to control the world",                                                icon: "🧠" },
  { name: "Eva McCulloch",       universe: "CW",     scheme: "Replace the real world with her mirror dimension",                                                 icon: "🪞" },
  { name: "Reign",               universe: "CW",     scheme: "Purge Earth of sin as World Killer",                                                              icon: "☀" },
  { name: "Non",                 universe: "CW",     scheme: "Mind-control all humans into subservience",                                                       icon: "🌀" },
  { name: "Agent Liberty",       universe: "CW",     scheme: "Incite humanity to exterminate metahumans",                                                       icon: "🗽" },
  { name: "Mallus",              universe: "CW",     scheme: "Break free of his prison and devour all time",                                                    icon: "😈" },
  { name: "Cicada",              universe: "CW",     scheme: "Systematically hunt and kill every metahuman alive on Earth",                                     icon: "🪲" },
  { name: "Bloodwork",           universe: "CW",     scheme: "Weaponise blood control to achieve biological immortality",                                       icon: "🩸" },
  { name: "Cayden James",        universe: "CW",     scheme: "Turn cyber-terrorism into world-ending leverage over Star City",                                  icon: "💻" },
  // The Boys
  { name: "Homelander",          universe: "TB",     scheme: "Maintain iron control over Vought and all supes",                                                 icon: "🔴" },
  { name: "Stormfront",          universe: "TB",     scheme: "Weaponize supes for ideological supremacy",                                                       icon: "⚡" },
  { name: "Soldier Boy",         universe: "TB",     scheme: "Reclaim relevance through ruthless retribution",                                                  icon: "🛡" },
  { name: "The Deep",            universe: "TB",     scheme: "Claw back standing in The Seven by any means",                                                    icon: "🌊" },
  { name: "A-Train",             universe: "TB",     scheme: "Outrun his past and stay relevant at any cost",                                                   icon: "💨" },
  { name: "Black Noir",          universe: "TB",     scheme: "Carry out Vought's kill-orders without hesitation",                                               icon: "🖤" },
  { name: "Translucent",         universe: "TB",     scheme: "Infiltrate and expose enemies from the shadows",                                                  icon: "👁" },
  { name: "Lamplighter",         universe: "TB",     scheme: "Burn any loose end Vought orders him to eliminate",                                               icon: "🔥" },
  { name: "Crimson Countess",    universe: "TB",     scheme: "Exploit celebrity supe fame while hiding Payback's darkest atrocities",                           icon: "❤" },
  { name: "Blue Hawk",           universe: "TB",     scheme: "Use Vought backing to enforce brutal vigilante justice with zero accountability",                  icon: "🦅" },
  { name: "Gunpowder",           universe: "TB",     scheme: "Leverage gun-based powers and political connections to serve Vought's agenda",                    icon: "🔫" },
  // Power Rangers
  { name: "Rita Repulsa",        universe: "PR",     scheme: "Conquer Earth and destroy the Power Rangers once and for all",                                    icon: "🧙" },
  { name: "Lord Zedd",           universe: "PR",     scheme: "Reclaim dominion as Emperor of Evil across the entire universe",                                  icon: "👑" },
  { name: "Thrax",               universe: "PR",     scheme: "Unite all villains to destroy Sentinel Knight and avenge his parents' defeat",                    icon: "⚔" },
  { name: "Dark Specter",        universe: "PR",     scheme: "Drain Zordon's power and conquer the entire universe as Grand Monarch",                           icon: "🌑" },
  { name: "Astronema",           universe: "PR",     scheme: "Serve Dark Specter and obliterate the Space Rangers utterly",                                     icon: "🌑" },
  { name: "Divatox",             universe: "PR",     scheme: "Plunder the galaxy and eliminate Zordon's lasting legacy",                                        icon: "🏴‍☠️" },
  { name: "Scorpius",            universe: "PR",     scheme: "Gather the Quasar Sabers to achieve ultimate power over the galaxy",                              icon: "🦂" },
  { name: "Trakeena",            universe: "PR",     scheme: "Destroy everything Kendrix Morgan sacrificed herself to protect",                                 icon: "🦂" },
  { name: "Ransik",              universe: "PR",     scheme: "Dominate the past and reshape the future entirely for mutantkind",                                icon: "🧬" },
  { name: "Master Org",          universe: "PR",     scheme: "Exterminate humanity and restore Orgs as rulers of the Wild Force world",                        icon: "🌿" },
  { name: "Lothor",              universe: "PR",     scheme: "Collect enough ninja souls to open the Abyss of Evil and conquer Earth",                          icon: "🌀" },
  { name: "Mesogog",             universe: "PR",     scheme: "De-evolve humanity back to the prehistoric age of dinosaurs",                                     icon: "🦖" },
  { name: "Gruumm",              universe: "PR",     scheme: "Conquer Earth for the Troobian Empire and feed the Magnificence",                                 icon: "💀" },
  { name: "Venjix",              universe: "PR",     scheme: "Wipe out the last of humanity and absorb all computer systems as one",                            icon: "🤖" },
  { name: "Master Xandred",      universe: "PR",     scheme: "Flood the Sanzu River into the human world and rule it in darkness",                              icon: "🌊" },
  { name: "Vrak",                universe: "PR",     scheme: "Betray his own royal family to reshape Earth under Warstar dominion",                             icon: "👽" },
  { name: "Sledge",              universe: "PR",     scheme: "Collect every powerful Energem and sell them across the galaxy",                                  icon: "⛓" },
  { name: "Madame Odius",        universe: "PR",     scheme: "Steal ninja power through deception and claim the Ninja Nexus Prism",                             icon: "🎭" },
  { name: "Void Knight",         universe: "PR",     scheme: "Resurrect his beloved at any cost — even destroying the Dino Fury Rangers",                      icon: "🗡" },
  // Star Wars
  { name: "Darth Vader",         universe: "SW",     scheme: "Serve the Emperor and crush all Rebel resistance across the galaxy",                              icon: "⬛" },
  { name: "Emperor Palpatine",   universe: "SW",     scheme: "Rule the galaxy as God-Emperor through absolute Sith mastery",                                   icon: "👁" },
  { name: "Kylo Ren",            universe: "SW",     scheme: "Destroy the last Jedi and rule the galaxy as Supreme Leader",                                    icon: "🔴" },
  { name: "Count Dooku",         universe: "SW",     scheme: "Reshape galactic politics through Separatist war and Sith manipulation",                         icon: "⚡" },
  { name: "Darth Maul",          universe: "SW",     scheme: "Rebuild his criminal empire and destroy those who humiliated him",                                icon: "🔴" },
  { name: "Grand Admiral Thrawn",universe: "SW",     scheme: "Conquer the New Republic through tactical genius and cultural study",                             icon: "🎨" },
  { name: "Moff Gideon",         universe: "SW",     scheme: "Harness Mandalorian power and dark science to rebuild the Empire",                               icon: "⚔" },
  { name: "Director Krennic",    universe: "SW",     scheme: "Complete the Death Star and claim his place at the Emperor's side",                               icon: "💀" },
  { name: "Grand Moff Tarkin",   universe: "SW",     scheme: "Rule through fear — the Death Star is the ultimate demonstration",                                icon: "🏛" },
  { name: "Boba Fett",           universe: "SW",     scheme: "Complete any bounty contract and cement his legacy as the galaxy's greatest hunter",             icon: "🎯" },
  { name: "The Grand Inquisitor",universe: "SW",     scheme: "Hunt every surviving Jedi to extinction on the Emperor's order",                                 icon: "🔺" },
  { name: "Jabba the Hutt",      universe: "SW",     scheme: "Expand Hutt cartel dominion and collect every debt owed to him",                                 icon: "🐸" },
  { name: "General Grievous",    universe: "SW",     scheme: "Collect Jedi lightsabers as trophies while executing Separatist conquest",                       icon: "🤖" },
  { name: "Darth Revan",         universe: "SW",     scheme: "Forge an empire through the combined power of both light and dark side",                         icon: "🌑" },
  // Animated
  { name: "Maleficent",          universe: "Animated", scheme: "Curse every soul who defies her and blanket the Moors in eternal darkness",                   icon: "🌑" },
  { name: "Ursula",              universe: "Animated", scheme: "Collect desperate souls through impossible bargains and seize Triton's trident",               icon: "🐙" },
  { name: "Evil Queen",          universe: "Animated", scheme: "Destroy Snow White and reclaim the title of the fairest through dark sorcery",                icon: "🍎" },
  { name: "Mother Gothel",       universe: "Animated", scheme: "Keep Rapunzel imprisoned forever as a living source of youth and immortality",                icon: "🌸" },
  { name: "Cruella de Vil",      universe: "Animated", scheme: "Skin one hundred and one Dalmatian puppies to create the ultimate fur coat",                  icon: "💀" },
  { name: "Yzma",                universe: "Animated", scheme: "Assassinate Emperor Kuzco and seize the Incan Empire through scheming brilliance",             icon: "⚗" },
  { name: "Queen of Hearts",     universe: "Animated", scheme: "Maintain absolute terrifying rule through arbitrary decrees — off with their heads",           icon: "❤" },
  // Gaming
  { name: "Albert Wesker",       universe: "Gaming",   scheme: "Inject Uroboros into humanity and rule the perfected survivors as an Ubermensch god",         icon: "🕶" },
  { name: "Sephiroth",           universe: "Gaming",   scheme: "Become one with the Planet by igniting a Meteor and absorbing the life stream as a god",      icon: "🌑" },
  { name: "The Illusive Man",    universe: "Gaming",   scheme: "Control the Reapers to place humanity at the apex of galactic civilization",                   icon: "🚬" },
  { name: "Handsome Jack",       universe: "Gaming",   scheme: "Brand Pandora's bandits as vermin and rule Hyperion as its god-emperor of efficiency",        icon: "🎭" },
  { name: "Vaas Montenegro",     universe: "Gaming",   scheme: "Hold the Rook Islands under pirate terror and feed every captive to his personal madness",    icon: "🏝" },
  { name: "Ardyn Izunia",        universe: "Gaming",   scheme: "Unravel Lucis's royal bloodline over two millennia of patient, exquisite revenge",             icon: "🎩" },
  { name: "Caius Ballad",        universe: "Gaming",   scheme: "Destroy the timeline itself to end the suffering of his immortal ward Yeul",                  icon: "💔" },
  { name: "Mother Miranda",      universe: "Gaming",   scheme: "Resurrect her dead daughter by fusing the Cadou fungus with a perfect host body",             icon: "🦅" },
  { name: "Ultimecia",           universe: "Gaming",   scheme: "Compress all time and space into a single moment she alone controls as a Time Witch god",     icon: "🕰" },
  { name: "Seymour Guado",       universe: "Gaming",   scheme: "Lead all of Spira into death and become the most powerful unsent the world has ever seen",    icon: "💀" },
  { name: "Kefka Palazzo",       universe: "Gaming",   scheme: "Drain the Warring Triad's power to become a god and revel in pure nihilistic destruction",    icon: "🎪" },
  { name: "GLaDOS",              universe: "Gaming",   scheme: "Run Aperture Science's test chambers with neurotoxin backup and cheerful passive-aggression",  icon: "🤖" },
  // Film
  { name: "Immortan Joe",        universe: "Film",     scheme: "Control the Wasteland through water monopoly and breed a warrior dynasty from his seed",       icon: "💀" },
  { name: "Agent Smith",         universe: "Film",     scheme: "Propagate himself through every mind in the Matrix and tear free from his purpose",           icon: "🕶" },
  { name: "President Snow",      universe: "Film",     scheme: "Maintain Capitol dominion over all twelve Districts through fear, roses, and the Games",      icon: "🌹" },
  { name: "Bill (Kill Bill)",    universe: "Film",     scheme: "Reclaim ownership over his deadliest pupil on his own timeline and terms",                     icon: "🗡" },
  { name: "O-Ren Ishii",         universe: "Film",     scheme: "Rule the Tokyo underworld as its queen and erase every humiliation with a Hattori Hanzo blade",icon: "☃" },
  { name: "Viktor (Underworld)", universe: "Film",     scheme: "Maintain vampire council supremacy by destroying every Lycan and any hybrid abomination",     icon: "🩸" },
  { name: "The Terminator",      universe: "Film",     scheme: "Locate and eliminate Sarah Connor before the Resistance can ever be born",                    icon: "🦾" },
  { name: "Carter Burke",        universe: "Film",     scheme: "Smuggle a live xenomorph past quarantine and make a fortune delivering it to Weyland-Yutani",  icon: "💼" },
  { name: "Ares (Xena)",         universe: "TV",       scheme: "Transform Xena back into his perfect warlord and rule humanity through her glorious chaos",    icon: "⚔" },
  { name: "Callisto",            universe: "TV",       scheme: "Destroy Xena's peace by burning everything she loves — starting with Gabrielle",              icon: "🔥" },
  { name: "Angelus",             universe: "TV",       scheme: "Torture the Scooby Gang psychologically and awaken Acathla to swallow the world into Hell",   icon: "🧛" },
  { name: "The Mayor",           universe: "TV",       scheme: "Complete his Ascension into a pure demon on Sunnydale's graduation day",                      icon: "🐍" },
  { name: "Cersei Lannister",    universe: "TV",       scheme: "Keep the Iron Throne for House Lannister by any means — poison, fire, or political ruin",     icon: "👑" },
  { name: "Ramsay Bolton",       universe: "TV",       scheme: "Break every captive utterly and hold the North through sadism and calculated terror",          icon: "🐕" },
  { name: "The Night King",      universe: "TV",       scheme: "Lead the Army of the Dead beyond the Wall and end the age of the living forever",             icon: "❄" },
  { name: "Petyr Baelish",       universe: "TV",       scheme: "Climb the chaos ladder until he sits atop every throne in Westeros with Sansa at his side",   icon: "🪙" },
];

export const VILLAIN_UNIVERSES = ["Marvel", "DC", "CW", "TB", "PR", "SW", "Animated", "Gaming", "Film", "TV"] as const;
export type VillainUniverse = typeof VILLAIN_UNIVERSES[number];
